#pragma once
#include <ISensor.hpp>
#include <Adafruit_MPRLS.h>

/**
 * @brief Data structure for MPRLS sensor readings
 * 
 */
class MPRLSData : public SensorData
{
public:
    MPRLSData() : SensorData("MPRLS") {}

    // Pressure (hPa)
    float pressure;

    // Metadata
    uint32_t timestamp;

    json toJSON() const override {
        json j;
        j["source"] = getSensorName();

        json sensorDataJson;
        sensorDataJson["pressure"] = pressure;
        sensorDataJson["timestamp"] = timestamp;

        j["sensorData"] = sensorDataJson;

        return j;
    }
};

/**
 * @brief MPRLS sensor class
 * 
 */
class MPRLSSensor : public ISensor
{
public:
    MPRLSSensor();
    bool init() override;
    bool updateData() override;

    /**
     * @brief Getter for the sensor data
     * 
     * @return a shared pointer to the MPRLSData structure containing the latest readings
     */
    std::shared_ptr<MPRLSData> getData();

private:
    // Interface to the MPRLS sensor using Adafruit library
    Adafruit_MPRLS _mprls;

    // Data generated by the sensor
    std::shared_ptr<MPRLSData> _data;
};
