#pragma once

#include <BNO055SensorInterface.hpp>
#include <SensorData.hpp>
#include <ISensor.hpp>

/**
 * @brief Data structure for BNO055 sensor readings
 * 
 */
class BNO055Data : public SensorData
{
public:
    BNO055Data() : SensorData("BNO055") {}

    // Calibration status
    uint8_t calibration_sys;
    uint8_t calibration_gyro;
    uint8_t calibration_accel;
    uint8_t calibration_mag;
    
    // Orientation (Euler angles in degrees)
    float orientation_x;
    float orientation_y;
    float orientation_z;
    
    // Angular velocity (rad/s)
    float angular_velocity_x;
    float angular_velocity_y;
    float angular_velocity_z;
    
    // Linear acceleration (m/s^2)
    float linear_acceleration_x;
    float linear_acceleration_y;
    float linear_acceleration_z;
    
    // Total acceleration (m/s^2)
    float acceleration_x;
    float acceleration_y;
    float acceleration_z;

    // Gravity vector (m/s^2)
    float gravity_x;
    float gravity_y;
    float gravity_z;
    
    // Magnetometer (microtesla)
    float magnetometer_x;
    float magnetometer_y;
    float magnetometer_z;
    
    // Quaternion orientation
    double quaternion_w;
    double quaternion_x;
    double quaternion_y;
    double quaternion_z;
    
    // Temperature (°C)
    float temperature;
    
    // Metadata
    uint32_t timestamp;
    
    json toJSON() const override {
        json j;
        j["source"] = getSensorName();

        json sensorDataJson;
        sensorDataJson["calibration_sys"] = calibration_sys;
        sensorDataJson["calibration_gyro"] = calibration_gyro;
        sensorDataJson["calibration_accel"] = calibration_accel;
        sensorDataJson["calibration_mag"] = calibration_mag;
        sensorDataJson["orientation_x"] = orientation_x;
        sensorDataJson["orientation_y"] = orientation_y;
        sensorDataJson["orientation_z"] = orientation_z;
        sensorDataJson["angular_velocity_x"] = angular_velocity_x;
        sensorDataJson["angular_velocity_y"] = angular_velocity_y;
        sensorDataJson["angular_velocity_z"] = angular_velocity_z;
        sensorDataJson["linear_acceleration_x"] = linear_acceleration_x;
        sensorDataJson["linear_acceleration_y"] = linear_acceleration_y;
        sensorDataJson["linear_acceleration_z"] = linear_acceleration_z;
        sensorDataJson["acceleration_x"] = acceleration_x;
        sensorDataJson["acceleration_y"] = acceleration_y;
        sensorDataJson["acceleration_z"] = acceleration_z;
        sensorDataJson["gravity_x"] = gravity_x;
        sensorDataJson["gravity_y"] = gravity_y;
        sensorDataJson["gravity_z"] = gravity_z;
        sensorDataJson["magnetometer_x"] = magnetometer_x;
        sensorDataJson["magnetometer_y"] = magnetometer_y;
        sensorDataJson["magnetometer_z"] = magnetometer_z;
        sensorDataJson["quaternion_w"] = quaternion_w;
        sensorDataJson["quaternion_x"] = quaternion_x;
        sensorDataJson["quaternion_y"] = quaternion_y;
        sensorDataJson["quaternion_z"] = quaternion_z;
        sensorDataJson["temperature"] = temperature;
        sensorDataJson["timestamp"] = timestamp;

        j["sensorData"] = sensorDataJson;

        return j;
    }
};

/**
 * @brief BNO055 sensor class
 * 
 */
class BNO055Sensor : public ISensor
{
public:
    BNO055Sensor();
    bool init() override;
    bool updateData() override;
    bool hardwareTest();

    /**
     * @brief Getter for the sensor data
     * 
     * @return a shared pointer to the BNO055Data structure containing the latest readings 
     */
    std::shared_ptr<BNO055Data> getData();

private:
    // Interface to the BNO055 sensor using low-level APIs
    BNO055SensorInterface _bno_interface;

    // Data generated by the sensor
    std::shared_ptr<BNO055Data> _data;
};

